### ISSUE TITLE
Trader is not TypeOf:

### ISSUE THREAD

**Issue by jesperom** [HallyG/HALs_Store#10]
I'm not really sure why this happens, anybody experienced this?
![image](https://user-images.githubusercontent.com/47032277/70382404-e4d36900-195b-11ea-8f95-ed944b8a0c90.png)

**Comment by syhrus** [comment]
It must be something hardcoded into the store code. Needs to be applied to either a man, vehicle, or ammobox. Weird.



Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network



-------- Original message --------

**Comment by HallyG** [comment]
Hi, this is going to be fixed in the next updated.

**Comment by HallyG** [comment]
Fixed in v1.5
