### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by vbr74** [HallyG/HALs_Store#2]
Hello, since I am unable to open a new pull request, I've done an issue (sorry for the inconvenience).

Here is my french translation of the stringtable, hope it can help :

`<Project name="HALs_store">
    <Package name="General">
	    <Key ID="STR_HALS_STORE_ACTION">
		    <Original>Store</Original>
		    <English>Store</English>
		    <French>Magasin</French>
			<German>Geschäft</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_ITEM_UNAVALIABLE">
		    <Original>Item unavaliable</Original>
		    <English>Item unavaliable</English>
		    <French>Item indisponible</French>
			<German>Gegenstand nicht verfügbar</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_ITEM_OUTOFSTOCK">
		    <Original>Insufficient stock</Original>
		    <English>Insufficient stock</English>
		    <French>Stocks insufissant</French>
			<German>Ausverkauft</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_ITEM_TOOEXPENSIVE">
		    <Original>Insufficient funds</Original>
		    <English>Insufficient funds</English>
		    <French>Fonds insufissant</French>
			<German>Zu wenig Geld</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<KEY ID="STR_HALS_STORE_ITEM_NOEQUIP">
			<Original>Unable to equip</Original>
		    <English>Unable to equip</English>
		    <French>Impossible de s'équiper</French>
			<German></German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_ITEM_NOCARGOSPACE">
		    <Original>Insufficient cargo space</Original>
		    <English>Insufficient cargo space</English>
		    <French>Pas assez d'espace disponible</French>
			<German>Nicht genug Platz</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_ITEM_PURCHASED">
		    <Original>purchased</Original>
		    <English>purchased</English>
		    <French>Acheté</French>
			<German>gekauft</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
	</Package>
	<Package name="Dialog">
	    <Key ID="STR_HALS_STORE_CHECKBOX_AFFORD">
		    <Original>Only show items which the player can afford</Original>
		    <English>Only show items which the player can afford</English>
		    <French>Ne montrer que les items achetables</French>
			<German>Zeige nur Gegenstände, die sich der Spieler leisten kann</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
	    <Key ID="STR_HALS_STORE_CHECKBOX_STOCK">
		    <Original>Only show items which are in stock</Original>
		    <English>Only show items which are in stock</English>
		    <French>Ne montrer que les items en stock</French>
			<German>Zeige nur Gegenstände, die auf Lager sind</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
	    <Key ID="STR_HALS_STORE_CHECKBOX_COMPATIBLE">
		    <Original>Only show items compatible with the player's equipped weapons</Original>
		    <English>Only show items compatible with the player's equipped weapons</English>
		    <French>Ne montrer que les items compatibles</French>
			<German>Zeige nur Gegenstände, die mit der ausgerüsteten Waffe des Spielers kompatibel sind</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
	    <Key ID="STR_HALS_STORE_CHECKBOX_EQUIP">
		    <Original>Equip item upon purchase (if possible)</Original>
		    <English>Equip item upon purchase (if possible)</English>
		    <French>Equiper une fois acheter (si possible)</French>
			<German>Gegenstand beim Kauf ausrüsten (wenn möglich)</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
	    <Key ID="STR_HALS_STORE_BUTTON_PURCHASE">
		    <Original>Purchase</Original>
		    <English>Purchase</English>
		    <French>Acheter</French>
			<German>Kaufen</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_TEXT_PRICE">
		    <Original>Price</Original>
		    <English>Price</English>
		    <French>Prix</French>
			<German>Preis</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_TEXT_INSTOCK">
		    <Original>IN STOCK</Original>
		    <English>IN STOCK</English>
		    <French>EN STOCK</French>
			<German>AUF LAGER</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_TEXT_NOSTOCK">
		    <Original>OUT OF STOCK</Original>
		    <English>OUT OF STOCK</English>
		    <French>INDISPONIVLE</French>
			<German>AUSVERKAUFT</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
		<Key ID="STR_HALS_STORE_LISTBOX_NOMONEY">
		    <Original>%1¢ more required</Original>
		    <English>%1¢ more required</English>
		    <French>%1¢ requis</French>
			<German>%1¢ mehr benötigt</German>
			<Russian></Russian>
			<Spanish></Spanish>
			<Italian></Italian>
		</Key>
	</Package>
</Project>
`

Best Regards,
Vbr74,
www.cana-multigaming.fr

**Comment by HallyG** [comment]
Added french translation to v1.4
