### ISSUE TITLE
Give Money & Vehicle Shop

### ISSUE THREAD

**Issue by RaidenKoizuma** [HallyG/HALs_Store#20]
The two features that I'm desperate for are ways to give players your money directly and a way to purchase vehicles. I've tried using other scripts for these, but they don't seem to work all that well. If these two things were possible this would be the best all in one shop script I've ever seen. Thank you.

**Comment by JustAdrian98** [comment]
You need to develop your own functions for that. You can base grad-moneyMenu for inspiration for creating your own functions.
