### ISSUE TITLE
persistence of the money system.

### ISSUE THREAD

**Issue by alevelasco9** [HallyG/HALs_Store#24]
Hello, I want to use this script for a campaign but I would need the complete inventory of the player (including money).  
which one could i use?

**Comment by svencc** [comment]
You have to slightly modify HAL; then you can combine it with GRAD_Persistence (https://github.com/gruppe-adler/grad-persistence)

You can look into my Project: https://github.com/svencc/hired_guns

Make a diff of my folder HALs/Addons with the one from the original HAL repository to find out the changes on the code you have to make.

There is no out-of-the-box solution; you have to do it on your own. It is not so much work.

**Comment by tigre437** [comment]
> Hola, quiero usar este script para una campaña pero necesitaría el inventario completo del jugador (incluido el dinero). ¿Cuál podría usar?

hello alevelasco, have you managed to do it? i am thinking of doing it but i would like to know if you managed to do it or if you made any progress?

**Comment by alevelasco9** [comment]
Hi! yes i could do it with a system persistent simple that another user helped to me
