### ISSUE TITLE
Possibility to give money for tasks completed?

### ISSUE THREAD

**Issue by AngusDLX** [HallyG/HALs_Store#4]
Me and my clan use K.P Liberation and A.L.I.V.E

We are always looking for a game mode where we could grow over time and when I saw this mod I was impressed with the quality of it but I have doubts about how to define a way to give money to the members of my clan based on the tasks that they complete ( based on kill I do not think it would look good since they would leave the teamplay in exchange for getting kills)

Maybe I've forgotten something in the manuals?

**Comment by HallyG** [comment]
Hi, try something like this (not tested)

init.sqf

```
if (isServer) then {
	addMissionEventHandler ["EntityKilled", {
		params ["_killed", "_killer", "_instigator"];
		
		if (isNull _instigator) then {_instigator = UAVControl vehicle _killer select 0};
		if (isNull _instigator) then {_instigator = _killer};
		
		if !(isNull _instigator && isNull killer) then {	
			if !(side group _killed in [civilian, side _instigator]) then {
				if !(_killed isEqualTo _instigator) then {
					[_instigator, 100] call HALs_money_fnc_addFunds;
				};
			};
		};
	}];
};
```
